### ISSUE TITLE
Implement the LIST_VOLUMES_PUBLISHED_NODES method

### ISSUE THREAD

**Issue by dimm0** [cernops/cvmfs-csi#10]
As mentioned in https://github.com/kubernetes/kubernetes/issues/84169#issuecomment-595400235, CSI drivers now have to implement the LIST_VOLUMES_PUBLISHED_NODES method, which significantly decreases the load on controller when the number of volumes is large.

I might make a PR soon, but if somebody else can do it quicker, it would be appreciated. Currently we can't use the driver, because the time of volume attach increases to tens of minutes (see the ticket)

**Comment by rochaporto** [comment]
Thanks, i'll check this soon.

Which versions of the sidecars are you using?

**Comment by dimm0** [comment]
I've updated to all latest recently. There's no reason to stay on earlier
quay.io/k8scsi/csi-provisioner:v1.5.0
quay.io/k8scsi/csi-attacher:v2.1.1
quay.io/k8scsi/csi-node-driver-registrar:v1.0.2 still, but might as well update to 1.2.0 (same with csi-node-driver-registrar)

**Comment by sfiligoi** [comment]
@rochaporto Any ETA when this could be implemented?

**Comment by rochaporto** [comment]
Hi @sfiligoi . Will be picking this up now along with the helm chart.

**Comment by sfiligoi** [comment]
@rochaporto Any updates?

**Comment by sfiligoi** [comment]
@rochaporto Any updates?

**Comment by rochaporto** [comment]
Sorry for the delay. I've merged the helm chart it's now easier to test this.

**Comment by gman0** [comment]
Hi @dimm0, we are overhauling the driver in #39. It no longer needs volume attachments. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
