### ISSUE TITLE
Command line flags provided to cvmfsplugin container fail at runtime 

### ISSUE THREAD

**Issue by Mansalu** [cernops/cvmfs-csi#13]
The command line arguments found below are rejected by the application:

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin.yaml#L51

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin.yaml#L52

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin.yaml#L56

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin.yaml#L57

This causes both deployments to enter `CrashLoopBackoff`

Each flag produces its own version of the following error message in the container:

```
flag provided but not defined: -metadatastorage
Usage of /csi-cvmfsplugin:
  -alsologtostderr
    	log to standard error as well as files
  -drivername string
    	name of the driver (default "csi-cvmfs")
  -endpoint string
    	CSI endpoint (default "unix://tmp/csi.sock")
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -nodeid string
    	node id
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

This can be reproduced by building the binary and container using the README `make` instructions.

Likewise this error also happens in the csi-cvmfsplugin-provisioner.yaml deployment.

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin-provisioner.yaml#L72

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin-provisioner.yaml#L73

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin-provisioner.yaml#L77

https://github.com/cernops/cvmfs-csi/blob/cf010f9cd957ea0b7875cd2966fbba2a23710685/deployments/kubernetes/csi-cvmfsplugin-provisioner.yaml#L78

**Comment by gman0** [comment]
Hi @Mansalu, we are overhauling the driver in #39. The cmd flags and their usage in helm / Kubernetes manifests are fixed in the PR. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
