### ISSUE TITLE
SC provisioner name should be pointing to `cvmfs.csi.cern.ch`

### ISSUE THREAD

**Issue by isantospardo** [cernops/cvmfs-csi#21]
SC provisioner name should be pointing to `cvmfs.csi.cern.ch`

Actions to be taken:
- Parametrize SC provisioner name
- Add default provisioner name value to `cvmfs.csi.cern.ch`

**Comment by gman0** [comment]
Superseded by https://github.com/cernops/cvmfs-csi/pull/39. Closing.
