### ISSUE TITLE
--drivername not passed to driver

### ISSUE THREAD

**Issue by innovate-invent** [cernops/cvmfs-csi#26]
https://github.com/cernops/cvmfs-csi/blob/e96e011380031690d9667706f7a9783915d8d52c/cmd/csi-cvmfsplugin/main.go#L51

The current release of this driver does not allow configuration of the driver name and requires it be set to the hard coded value of "cvmfsDriver".

**Comment by gman0** [comment]
Hi @innovate-invent, we are overhauling the driver in #39. The driver name should be correctly passed in the new version. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
