### ISSUE TITLE
Skip attach?

### ISSUE THREAD

**Issue by cyrilcros** [cernops/cvmfs-csi#29]
I was looking at the attacher container logs and saw this line:  `main.go:165] CSI driver does not support ControllerPublishUnpublish, using trivial handler`.  It might be worth doing this: https://kubernetes-csi.github.io/docs/skip-attach.html . Isn’t it relevant here?
I don’t know what kubernetes version this project supports...

**Comment by innovate-invent** [comment]
it is only possible when https://github.com/cernops/cvmfs-csi/issues/26 is resolved.

**Comment by innovate-invent** [comment]
I have this working in https://github.com/cernops/cvmfs-csi/pull/36

**Comment by gman0** [comment]
Hi @cyrilcros, we are overhauling the driver in #39. The new version provides `CSIDriver` object with `attachRequired: false`. Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.
