### ISSUE TITLE
Add affinity, tolerations and priorityClassName

### ISSUE THREAD

**Issue by isantospardo** [cernops/cvmfs-csi#32]
Right now, cvmfs-csi does not have functionality for affinity, tolerations and priorityClassName to daemonSets

https://github.com/cernops/cvmfs-csi/blob/master/deployments/helm/cvmfs-csi/templates/csi-cvmfsplugin.yaml

Adds  affinity, tolerations and priorityClassName functionality.

Reference:  https://github.com/cernops/cvmfs-csi/pull/31#issuecomment-806039776

**Comment by gman0** [comment]
Superseded by #39. Closing.
