### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by titansmc** [cernops/cvmfs-csi#37]
Hi,
Should we still use this CSI in case we want to mount CVMFS in k8s? Should we switch to something else?
Cheers.

**Comment by gman0** [comment]
Hi @titansmc,

this project is indeed a bit low on number of maintainers, but there will be a large overhaul in the near future.

**Comment by innovate-invent** [comment]
I have been making an attempt at maintaining this driver: https://github.com/cernops/cvmfs-csi/pull/36

https://hub.docker.com/r/brinkmanlab/csi-cvmfsplugin/tags

**Comment by gman0** [comment]
Hi @titansmc, just an update: we are overhauling the driver in #39. Sorry for the long wait! I'm closing this issue now, but please feel free to reopen, or open another one if you have comments or questions.
