### ISSUE TITLE
Consider using go modules

### ISSUE THREAD

**Issue by SEJeff** [cernops/cvmfs-csi#5]
Upstream go has created a system called [modules](https://blog.golang.org/migrating-to-go-modules) for dependency tracking so users don't need to vendor dependencies. Consider using this instead of Gopkg.lock and vendoring.

**Comment by rochaporto** [comment]
I've changed to use go modules in most of my go libraries, will do this one as well. Thanks.

**Comment by rochaporto** [comment]
The PR has a bit more than just the migration to go modules - a new Makefile and an updated layout for the git repo.

**Comment by SEJeff** [comment]
Great stuff, thanks so much!
