### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by almahmoud** [cernops/cvmfs-csi#9]
Since the original PR-ed chart (https://github.com/cernops/cvmfs-csi/pull/3), our chart has evolved and been tested in the wild for a few months now, becoming more configurable with support for local vs alien cache (with alien cache tested on NFS), as well as cache preloading capabilities. The current version that we are using is at: https://github.com/CloudVE/galaxy-cvmfs-csi-helm
I was looking to PR the chart upstream so that other users might use it and hopefully have a community spanning beyond our project working on developing/maintaining it. I was wondering if you'd recommend me close that PR and issue a new one similarly putting the chart under `deploy/helm` or if there is another way you'd prefer it PR-ed. I can transform the default values to be more generic and not pointing to our repositories if that is desirable. Let me know what the best way would be to contribute this back to the community!

**Comment by rochaporto** [comment]
Hi.

Thanks for this, i was started to review your chart from the other PR.

Yes, a new PR and storing it under deployments/helm would be perfect.

Ricardo

**Comment by rochaporto** [comment]
@almahmoud are you working on this one? Let me know, i'm happy to pick it up as well, i'm doing plenty of helm things these days anyway.

**Comment by almahmoud** [comment]
I was and then got sidetracked by other responsibilities... I'll get back to it very soon, sorry for the delay!

**Comment by almahmoud** [comment]
Closing this, conversation can move to https://github.com/cernops/cvmfs-csi/pull/14. Thank you for the help!
